### ISSUE TITLE
Status icons 404'ing for non-logged in users

### ISSUE THREAD

**Issue by revelt** [rootslab/bop#1]
Hi! I just noticed README very top icons:
- status
- views
- views 24h

are going to 404: https://sourcegraph.com/github.com/rootslab/bop for anybody who is not logged in to the `Sourcegraph` service. We should not expect all visitors to be logged in, so maybe let's remove the icons? Broken images make the project look abandoned... What do you think?

**Comment by rootslab** [comment]
Hi @revelt, I'm glad to hear that someone is using Bop ;) .. however, you are right, I didn't update my modules for a very long time, I need some help to update some dependencies for the testing suite, new versions of node, etc.. please take a look at my sample [pull request](https://github.com/rootslab/bop/pull/2), if you have working changes, please open a pull request, I will merge it as soon as possbile, I don't have any time now to do these modifications, sorry and thanks for your notice!
